# Generated by Django 3.0.7 on 2020-07-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=12)),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('reservation_from', models.DateTimeField()),
                ('reservation_to', models.DateTimeField()),
                ('total_persons', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_logo', models.CharField(max_length=200)),
                ('site_name', models.CharField(max_length=50)),
                ('site_info', models.TextField(max_length=300)),
                ('banner_image1', models.ImageField(upload_to='')),
                ('banner_image2', models.ImageField(upload_to='')),
                ('banner_image3', models.ImageField(upload_to='')),
                ('about', models.CharField(max_length=200)),
                ('about_description', models.TextField()),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('google_map_key', models.CharField(max_length=100)),
                ('google_map_latitude', models.CharField(max_length=100)),
                ('google_map_longitude', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('menu_price', models.FloatField()),
                ('menu_description', models.TextField()),
                ('menu_photo', models.ImageField(upload_to='')),
                ('menu_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resto.MenuType')),
            ],
        ),
    ]
