# Generated by Django 3.0.7 on 2020-07-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0003_auto_20200729_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='banner_image1',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='banner_image2',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='banner_image3',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
