# Generated by Django 3.0.7 on 2020-07-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0004_auto_20200729_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
