# Generated by Django 3.0.7 on 2020-08-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0006_gallary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='gallery/')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallary',
        ),
    ]
