# Generated by Django 3.0.7 on 2020-08-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0007_auto_20200801_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_profile', models.ImageField(upload_to='uploads/')),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_review', models.TextField(max_length=300)),
            ],
        ),
    ]
