# Generated by Django 3.0.7 on 2020-08-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0008_customerreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_logo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
